'use client';

import React, { useState, useEffect } from 'react';
import { 
  Bell, 
  User, 
  Home, 
  FileText, 
  Settings, 
  Package, 
  Clock, 
  Users, 
  Activity, 
  TrendingUp, 
  AlertTriangle, 
  CheckCircle, 
  XCircle,
  Plus,
  Shield,
  Key,
  Wrench,
  BarChart3,
  Menu,
  Search,
  MoreHorizontal
} from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, PieChart, Pie, Cell, ResponsiveContainer, AreaChart, Area } from 'recharts';

// Mock data - replace with real API calls
const dashboardStats = {
  masterCatalog: {
    total: 608,
    hardware: 245,
    pharmacy: 210,
    grocery: 153
  },
  pendingRequests: 12,
  apiConsumers: 142,
  todayApiCalls: {
    total: 45210,
    successRate: 99.8,
    rate: 1.78
  }
};

const apiTrafficData = [
  { time: '02:00', requests: 800, latency: 52 },
  { time: '04:00', requests: 1200, latency: 48 },
  { time: '06:00', requests: 1800, latency: 45 },
  { time: '08:00', requests: 2400, latency: 38 },
  { time: '10:00', requests: 3200, latency: 35 },
  { time: '12:00', requests: 3800, latency: 41 },
  { time: '14:00', requests: 4200, latency: 39 },
  { time: '16:00', requests: 3600, latency: 42 },
  { time: '18:00', requests: 2800, latency: 46 },
  { time: '20:00', requests: 2000, latency: 48 },
  { time: '22:00', requests: 1400, latency: 44 },
  { time: '24:00', requests: 1000, latency: 50 }
];

const segmentData = [
  { name: 'Hardware', value: 56, color: '#3b82f6' },
  { name: 'Pharmacy', value: 29, color: '#10b981' },
  { name: 'Grocery', value: 15, color: '#f59e0b' }
];
const pendingRequests = [
  { id: 'REQ-001', product: 'Lysol Disinfectant Spray', category: 'Cleaning Products', user: 'juan@smestore.ph' },
  { id: 'REQ-002', product: 'Amoxicillin 500mg', category: 'Antibiotics', user: 'maria@pharmacy.ph' },
  { id: 'REQ-003', product: 'Bosny Spray Paint', category: 'Hardware Paint', user: 'carlos@hardware.ph' },
  { id: 'REQ-004', product: 'Lucky Me Pancit Canton', category: 'Instant Noodles', user: 'anna@grocery.ph' },
  { id: 'REQ-005', product: 'Biogesic Paracetamol', category: 'Pain Relief', user: 'peter@drugstore.ph' }
];

const auditLogs = [
  { time: '10:42 AM', action: 'API Key generated by User "juan@smestore.ph"', user: 'IP: 172.x.x.17', type: 'info' },
  { time: '10:40 AM', action: 'Rate Limit reached for key daas_prod_Baxm1..', user: 'IP: 172.x.x.17', type: 'warning' },
  { time: '10:38 AM', action: 'Product approved', admin: 'Super Admin Alex', type: 'success' },
  { time: '10:35 AM', action: 'New user registration', user: 'newuser@business.ph', type: 'info' },
  { time: '10:32 AM', action: 'Suspicious login attempt', user: 'unknown', type: 'error' },
  { time: '10:30 AM', action: 'System backup completed', system: 'auto', type: 'success' }
];

export default function BluishAdminDashboard() {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [currentTime, setCurrentTime] = useState(new Date());

  useEffect(() => {
    const timer = setInterval(() => setCurrentTime(new Date()), 1000);
    return () => clearInterval(timer);
  }, []);

  return (
    <div className="min-h-screen bg-slate-950 text-white">
      {/* Header */}
      <header className="bg-slate-900/90 border-b border-slate-800/50 px-4 py-3 backdrop-blur-sm">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <button 
              onClick={() => setSidebarOpen(!sidebarOpen)}
              className="p-2 rounded-lg hover:bg-slate-800/50 transition-colors lg:hidden"
            >
              <Menu className="w-5 h-5" />
            </button>
            <div className="flex items-center space-x-3">
              <div className="w-8 h-8 bg-gradient-to-r from-blue-500 to-cyan-500 rounded-lg flex items-center justify-center">
                <Package className="w-5 h-5 text-white" />
              </div>
              <div>
                <h1 className="text-xl font-bold bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">
                  InventaAPI
                </h1>
                <p className="text-xs text-slate-400 -mt-1">Admin Control Center</p>
              </div>
            </div>
          </div>
          
          <div className="flex items-center space-x-4">
            <div className="relative">
              <Bell className="w-5 h-5 text-slate-400 hover:text-white cursor-pointer transition-colors" />
              <span className="absolute -top-1 -right-1 w-3 h-3 bg-blue-500 rounded-full flex items-center justify-center">
                <span className="text-xs font-bold text-white">1</span>
              </span>
            </div>
            <div className="flex items-center space-x-2">
              <div className="w-8 h-8 bg-gradient-to-r from-blue-500 to-cyan-500 rounded-full flex items-center justify-center">
                <span className="text-sm font-bold">SA</span>
              </div>
              <div className="hidden md:block">
                <p className="text-sm font-medium">Super Admin</p>
                <p className="text-xs text-slate-400">Alex</p>
              </div>
            </div>
          </div>
        </div>
      </header>

      <div className="flex">
        {/* Sidebar */}
        <aside className={`${sidebarOpen ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-50 w-16 bg-slate-900/95 border-r border-slate-800/50 transform transition-transform duration-200 ease-in-out lg:translate-x-0 lg:static lg:inset-0 backdrop-blur-sm`}>
          <nav className="mt-8 px-2 space-y-2">
            {[
              { icon: Home, active: true },
              { icon: Bell },
              { icon: Users },
              { icon: FileText },
              { icon: Settings }
            ].map((item, index) => (
              <a 
                key={index}
                href="#"
                className={`flex items-center justify-center w-12 h-12 rounded-xl transition-all duration-200 ${
                  item.active 
                    ? 'bg-gradient-to-r from-blue-500/20 to-cyan-500/20 text-blue-400 border border-blue-500/30 shadow-lg shadow-blue-500/10' 
                    : 'text-slate-400 hover:text-white hover:bg-slate-800/50'
                }`}
              >
                <item.icon className="w-5 h-5" />
              </a>
            ))}
          </nav>
        </aside>

        {/* Main Content */}
        <main className="flex-1 p-6 space-y-6 overflow-auto bg-slate-950">
          {/* Top Grid - 4 Metric Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6">
            {/* Master Product Catalog */}
            <div className="bg-gradient-to-br from-slate-900/80 to-slate-800/80 rounded-2xl p-6 border border-slate-700/50 backdrop-blur-sm hover:border-blue-500/30 transition-all duration-300">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-sm font-medium text-slate-300">Master Product Catalog</h3>
                <MoreHorizontal className="w-4 h-4 text-slate-500" />
              </div>
              <div className="text-4xl font-bold text-white mb-3">608</div>
              <div className="space-y-2">
                <div className="flex items-center justify-between text-xs">
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 rounded-full bg-blue-400"></div>
                    <span className="text-slate-400">Hardware:</span>
                  </div>
                  <span className="text-white font-medium">245</span>
                </div>
                <div className="flex items-center justify-between text-xs">
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 rounded-full bg-green-400"></div>
                    <span className="text-slate-400">Pharmacy:</span>
                  </div>
                  <span className="text-white font-medium">210</span>
                </div>
                <div className="flex items-center justify-between text-xs">
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 rounded-full bg-yellow-400"></div>
                    <span className="text-slate-400">Grocery:</span>
                  </div>
                  <span className="text-white font-medium">153</span>
                </div>
              </div>
            </div>

            {/* Pending Requests */}
            <div className="bg-gradient-to-br from-slate-900/80 to-slate-800/80 rounded-2xl p-6 border border-slate-700/50 backdrop-blur-sm hover:border-yellow-500/30 transition-all duration-300">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-sm font-medium text-slate-300">Pending Requests</h3>
                <AlertTriangle className="w-5 h-5 text-yellow-400" />
              </div>
              <div className="text-4xl font-bold text-white mb-3">12</div>
              <p className="text-xs text-slate-400">Awaiting admin review</p>
            </div>
            {/* API Consumers */}
            <div className="bg-gradient-to-br from-slate-900/80 to-slate-800/80 rounded-2xl p-6 border border-slate-700/50 backdrop-blur-sm hover:border-green-500/30 transition-all duration-300">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-sm font-medium text-slate-300">API Consumers</h3>
                <TrendingUp className="w-5 h-5 text-green-400" />
              </div>
              <div className="text-4xl font-bold text-white mb-1">142</div>
              <div className="text-xs text-green-400 flex items-center">
                <span>Active Users</span>
                <div className="ml-2 w-8 h-4 bg-green-500/20 rounded-full flex items-center">
                  <div className="w-2 h-2 bg-green-400 rounded-full ml-1"></div>
                </div>
              </div>
            </div>

            {/* Today's API Calls */}
            <div className="bg-gradient-to-br from-slate-900/80 to-slate-800/80 rounded-2xl p-6 border border-slate-700/50 backdrop-blur-sm hover:border-blue-500/30 transition-all duration-300">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-sm font-medium text-slate-300">Today's API Calls</h3>
                <Activity className="w-5 h-5 text-blue-400" />
              </div>
              <div className="text-4xl font-bold text-white mb-1">45,210</div>
              <div className="text-xs text-slate-400">
                <span className="text-green-400">Success rate: 99.8%</span>
              </div>
            </div>
          </div>

          {/* Middle Grid - 3 Wide Cards */}
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            {/* API Contacts - Left Column */}
            <div className="lg:col-span-3 bg-gradient-to-br from-slate-900/80 to-slate-800/80 rounded-2xl p-6 border border-slate-700/50 backdrop-blur-sm">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-sm font-medium text-slate-300">API Contacts</h3>
                <MoreHorizontal className="w-4 h-4 text-slate-500" />
              </div>
              <div className="space-y-6">
                <div className="text-center">
                  <div className="text-2xl font-bold text-white">37.3M</div>
                  <div className="text-xs text-slate-400">Requests</div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-green-400">99.8%</div>
                  <div className="text-xs text-slate-400">Success</div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-blue-400">1.78</div>
                  <div className="text-xs text-slate-400">Rate</div>
                </div>
              </div>
            </div>
            {/* API Traffic Overview - Center Column */}
            <div className="lg:col-span-6 bg-gradient-to-br from-slate-900/80 to-slate-800/80 rounded-2xl p-6 border border-slate-700/50 backdrop-blur-sm">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h3 className="text-sm font-medium text-slate-300">API Traffic Overview</h3>
                  <p className="text-xs text-slate-500">Real-time requests the last 24 hours</p>
                </div>
                <div className="text-xs text-slate-400">Last 24 hours</div>
              </div>
              <ResponsiveContainer width="100%" height={160}>
                <AreaChart data={apiTrafficData}>
                  <defs>
                    <linearGradient id="colorRequests" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.3}/>
                      <stop offset="95%" stopColor="#3b82f6" stopOpacity={0.05}/>
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="#374151" opacity={0.3} />
                  <XAxis dataKey="time" stroke="#9CA3AF" fontSize={10} />
                  <YAxis stroke="#9CA3AF" fontSize={10} />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: '#1F2937', 
                      border: '1px solid #374151',
                      borderRadius: '8px',
                      color: '#F9FAFB',
                      fontSize: '12px'
                    }}
                  />
                  <Area 
                    type="monotone" 
                    dataKey="requests" 
                    stroke="#3b82f6" 
                    strokeWidth={2}
                    fillOpacity={1}
                    fill="url(#colorRequests)"
                  />
                </AreaChart>
              </ResponsiveContainer>
              <div className="mt-2 flex items-center justify-center space-x-4 text-xs">
                <span className="text-slate-400">< 100ms</span>
                <div className="w-1 h-1 bg-slate-600 rounded-full"></div>
                <span className="text-green-400">Peak: 4.2K req/h</span>
              </div>
            </div>
            {/* Data Consumption by Segment - Right Column */}
            <div className="lg:col-span-3 bg-gradient-to-br from-slate-900/80 to-slate-800/80 rounded-2xl p-6 border border-slate-700/50 backdrop-blur-sm">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-sm font-medium text-slate-300">Data Consumption by Segment</h3>
              </div>
              <ResponsiveContainer width="100%" height={120}>
                <PieChart>
                  <Pie
                    data={segmentData}
                    cx="50%"
                    cy="50%"
                    innerRadius={30}
                    outerRadius={60}
                    paddingAngle={2}
                    dataKey="value"
                  >
                    {segmentData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: '#1F2937', 
                      border: '1px solid #374151',
                      borderRadius: '8px',
                      color: '#F9FAFB',
                      fontSize: '12px'
                    }}
                  />
                </PieChart>
              </ResponsiveContainer>
              <div className="mt-2 space-y-1">
                {segmentData.map((item, index) => (
                  <div key={index} className="flex items-center justify-between text-xs">
                    <div className="flex items-center">
                      <div 
                        className="w-2 h-2 rounded-full mr-2" 
                        style={{ backgroundColor: item.color }}
                      ></div>
                      <span className="text-slate-400">{item.name}</span>
                    </div>
                    <span className="font-medium text-white">{item.value}%</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
          {/* Bottom Grid */}
          <div className="grid grid-cols-1 xl:grid-cols-12 gap-6">
            {/* Priority Review Queue - Left */}
            <div className="xl:col-span-4 bg-gradient-to-br from-slate-900/80 to-slate-800/80 rounded-2xl p-6 border border-slate-700/50 backdrop-blur-sm">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-sm font-medium text-slate-300">Priority Review Queue</h3>
                <span className="text-xs text-slate-500">Top Pending Product Request</span>
              </div>
              <div className="space-y-3">
                {[
                  { product: 'Lysol Disinfectant Spray', category: 'Cleaning', id: 'REQ-001', status: 'Approve' },
                  { product: 'Amoxicillin 500mg', category: 'Antibiotics', id: 'REQ-002', status: 'Reject' },
                  { product: 'Bosny Spray Paint', category: 'Hardware', id: 'REQ-003', status: 'Approve' }
                ].map((request, index) => (
                  <div key={index} className="flex items-center justify-between p-3 bg-slate-800/50 rounded-lg border border-slate-700/30">
                    <div className="flex items-center space-x-3">
                      <div className="w-8 h-8 bg-slate-700 rounded-lg flex items-center justify-center">
                        <Package className="w-4 h-4 text-slate-400" />
                      </div>
                      <div>
                        <h4 className="text-sm font-medium text-white">{request.product}</h4>
                        <div className="flex items-center space-x-2 text-xs text-slate-400">
                          <span>{request.category}</span>
                          <span>•</span>
                          <span>{request.id}</span>
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center space-x-1">
                      <button className={`px-3 py-1 text-xs font-medium rounded-lg transition-colors ${
                        request.status === 'Approve' 
                          ? 'bg-green-600/20 text-green-400 border border-green-500/30' 
                          : 'bg-red-600/20 text-red-400 border border-red-500/30'
                      }`}>
                        {request.status}
                      </button>
                      <button className="px-3 py-1 text-xs font-medium rounded-lg bg-slate-700/50 text-slate-400 border border-slate-600/30">
                        {request.status === 'Approve' ? 'Reject' : 'Approve'}
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            {/* Quick Actions - Center */}
            <div className="xl:col-span-3 bg-gradient-to-br from-slate-900/80 to-slate-800/80 rounded-2xl p-6 border border-slate-700/50 backdrop-blur-sm">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-sm font-medium text-slate-300">Quick Actions</h3>
              </div>
              <div className="space-y-2">
                {[
                  { icon: Plus, label: 'Add New Product', color: 'bg-blue-600/20 text-blue-400 border-blue-500/30' },
                  { label: 'Review Crowdsourcing', color: 'bg-slate-700/50 text-slate-400 border-slate-600/30' },
                  { label: 'System Maintenance Mode', color: 'bg-slate-700/50 text-slate-400 border-slate-600/30' },
                  { label: 'Security Settings', color: 'bg-slate-700/50 text-slate-400 border-slate-600/30' },
                  { label: 'API Key Management', color: 'bg-slate-700/50 text-slate-400 border-slate-600/30' }
                ].map((action, index) => (
                  <button 
                    key={index}
                    className={`w-full flex items-center p-3 ${action.color} rounded-lg border transition-all duration-200 text-left hover:scale-[1.02]`}
                  >
                    {action.icon && <action.icon className="w-4 h-4 mr-2" />}
                    <span className="text-xs font-medium">{action.label}</span>
                  </button>
                ))}
              </div>
            </div>

            {/* Live Security & Audit Feed */}
            <div className="xl:col-span-5 bg-gradient-to-br from-slate-900/80 to-slate-800/80 rounded-2xl p-6 border border-slate-700/50 backdrop-blur-sm">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-sm font-medium text-slate-300">Live Security & Audit Feed</h3>
              </div>
              <div className="space-y-2 max-h-48 overflow-y-auto">
                {auditLogs.slice(0, 6).map((log, index) => (
                  <div key={index} className="flex items-center space-x-3 p-2 bg-slate-800/30 rounded-lg border border-slate-700/20">
                    <div className={`w-1.5 h-1.5 rounded-full ${
                      log.type === 'success' ? 'bg-green-400' :
                      log.type === 'warning' ? 'bg-yellow-400' :
                      log.type === 'error' ? 'bg-red-400' : 'bg-blue-400'
                    }`}></div>
                    <span className="text-xs font-mono text-slate-400 w-16">{log.time}</span>
                    <span className="text-xs text-slate-300 flex-1">{log.action}</span>
                    <span className="text-xs text-blue-400">{log.user}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </main>
      </div>
      {/* Overlay for mobile sidebar */}
      {sidebarOpen && (
        <div 
          className="fixed inset-0 bg-black bg-opacity-50 z-40 lg:hidden"
          onClick={() => setSidebarOpen(false)}
        ></div>
      )}
    </div>
  );
}